
create table discrepancy_dw(
	execworkcenter VARCHAR(8),
	atano CHAR(5), 
	corrosionrelated CHAR(1), 
	trackid VARCHAR(50), 
	applicablity VARCHAR(50), 
	description VARCHAR(200), 
	discrepancytype VARCHAR(50), 
	maintphase VARCHAR(50), 
	partsrequireddesc VARCHAR(50), 
	majoritemdesc VARCHAR(50), 
	serialno VARCHAR(50), 
	execdocno CHAR(14), 
	discrepencycreationdate timestamp, 
	aircraftregno INT, 
	currentdiscrepancystatusdesc VARCHAR(50), 
	zone VARCHAR(50), 
	positioncode VARCHAR(50), 
	corrosionrelateddesc VARCHAR(50), 
	sourcetask_discrepancy VARCHAR(50), 
	customername VARCHAR(50), 
	partno VARCHAR(50), 
	doctypedesc VARCHAR(50), 
	sourcetaskdescription VARCHAR(50), 
	executionstatus VARCHAR(50), 
	componentid VARCHAR(50), 
	execstation VARCHAR(50), 
	ou INT, 
	majoritem CHAR(1), 
	execphase VARCHAR(50), 
	packageno VARCHAR(50), 
	partsrequired CHAR(1), 
	sourcetask VARCHAR(50), 
	currentdiscrepancystatus VARCHAR(5), 
	doctype VARCHAR(50), 
	execcategory VARCHAR(50), 
	discrepancycategory VARCHAR(50), 
	discrepancyno VARCHAR(4), 
	taskno VARCHAR(50), 
	discrepancytypedesc VARCHAR(50), 
	customercode VARCHAR(50), 
	aircraftmodel CHAR(4), 
	execdoctype VARCHAR(50)
);

select * from discrepancy_dw;